import { expect, test } from "@playwright/test";
import { updateCartRuleMutation } from "../../../../../mutations/cart-rules/update-cart-rule-api-mutation";
import { DBClient } from "../../../../../utils/dbClient";
import { GraphQLClient } from "../../../../../utils/adminApiClient";
import * as fs from "fs";
import path from "path";

test.describe("update cart-rule via GraphQL API", () => {
    let apiClient: GraphQLClient;
    apiClient = new GraphQLClient(GraphQLClient.baseURL);

    const createCustomerGroupResponse = fs.readFileSync(
        "create-customer-group-createResponse.json",
        "utf-8"
    );
    const cre = JSON.parse(createCustomerGroupResponse);
    console.log("Create customer group Response Data:", cre);
    const customer_group_id = Number(cre.createCustomerGroup.customerGroup.id);
    console.log("customer group ID to update:", customer_group_id);

    const createCartRuleResponse= fs.readFileSync(
        "create-cart-rule-createResponse.json",
        "utf-8"
    )

    const creCartResponse = JSON.parse(createCartRuleResponse);
    console.log("Create cart rule response:", creCartResponse);
    const create_cart_id = Number(creCartResponse.createCartRule.cartRule.id);

    const availableFromTo = getNowAndAfter3DaysFormatted();
    console.log("Available From:", availableFromTo.from);
    console.log("Available To:", availableFromTo.to);

    function formatDateTime(date: Date): string {
        const pad = (n: number) => n.toString().padStart(2, "0");

        return (
            `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(
                date.getDate()
            )} ` +
            `${pad(date.getHours())}:${pad(date.getMinutes())}:${pad(
                date.getSeconds()
            )}`
        );
    }

    function getNowAndAfter3DaysFormatted() {
        const now = new Date();
        const after3Days = new Date(now);
        after3Days.setDate(now.getDate() + 3);

        return {
            from: formatDateTime(now),
            to: formatDateTime(after3Days),
        };
    }
    test('update cart-rule via graphQL api', async () => {
        const randomSuffix = Date.now();
        const availableFromTo = getNowAndAfter3DaysFormatted();

        const updateCartRuleCredentials = {    
            name: `update-First Cart Rule (5%)${randomSuffix}`,
            description: `update-You can avail 5% off by using this cart rule.${randomSuffix}`,
            channels: [1],
            customerGroups: [customer_group_id],
            status: true,
            couponType: 1,
            useAutoGeneration: true,
            couponCode: `update_ABCDE_${randomSuffix}`,
            usesPerCoupon: 1,
            usagePerCustomer: 1,
            startsFrom: availableFromTo.from,
            endsTill: availableFromTo.to,
            sortOrder: 0,
            timesUsed: 1,
            conditionType: true,
            conditions: [{
                attribute: "cart|base_sub_total",
                operator: ">=",
                attributeType: "price",
                value: "5",
            },	{
                attribute: "product|category_ids",
                operator: "{}",
                attributeType: "multiselect",
                value: ["1", "3"],
            },	{
                attribute: "cart|payment_method",
                operator: "==",
                attributeType: "select",
                value: "cashondelivery",
            },	{
                attribute: "cart|items_qty",
                operator: "==",
                attributeType: "integer",
                value: "10",
            },	{
                attribute: "product|children::sku",
                operator: "!{}",
                attributeType: "text",
                value: "home-decor",
            }],
            usesAttributeConditions: true,
            actionType: "FixedAmount",
            discountAmount: 5,
            discountQuantity: 2,
            discountStep: 1,
            applyToShipping: true,
            freeShipping: true,
            endOtherRules: true,
            autogeneratedCoupons: {
                couponQty: 10,
                codeLength: 10,
                codeFormat: "ALPHABETICAL",
                codePrefix: "",
                codeSuffix: "",
            }
    
        };

        /**
         * Execute create CartRule mutation
         */
        const updateCartRuleResponse = await apiClient.execute(updateCartRuleMutation, {
                id: create_cart_id,
                input: updateCartRuleCredentials
        }, true);

        console.log('update cart rule Response:', updateCartRuleResponse);

        const filePath = path.resolve(process.cwd(), "update-cart-rule-createResponse.json");

        fs.writeFileSync(filePath, JSON.stringify(updateCartRuleResponse, null, 2), "utf-8");

        expect(updateCartRuleResponse.updateCartRule.success).toBe(true);
        expect(updateCartRuleResponse.updateCartRule.message).toContain('Cart Rule updated successfully.');
        expect(updateCartRuleResponse.updateCartRule.cartRule.name).not.toEqual(updateCartRuleCredentials.name);
        expect(updateCartRuleResponse.updateCartRule.cartRule.description).not.toEqual(updateCartRuleCredentials.description);

    });
});
